//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFF
{
    public partial class BoardSetup
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm
            form1;

        protected global::System.Web.UI.WebControls.Label
            ErrorMessageLabel;

        protected global::System.Web.UI.WebControls.Label
            FullNameLabel;

        protected global::System.Web.UI.WebControls.Label
            RoleLabel;

        protected global::System.Web.UI.WebControls.Panel
            TeamLeaderAssignmentPanel;

        protected global::System.Web.UI.WebControls.Label
            AssignedTeamLabel;

        protected global::System.Web.UI.WebControls.Panel
            TeamSelectionPanel;

        protected global::System.Web.UI.WebControls.DropDownList
            TeamDropDownList;

        protected global::System.Web.UI.WebControls.Panel
            ShiftSelectionPanel;

        protected global::System.Web.UI.WebControls.DropDownList
            ShiftDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ProductionLineDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ProductDropDownList;

        protected global::System.Web.UI.WebControls.TextBox
            BoardDateTextBox;

        protected global::System.Web.UI.WebControls.Label
            ReadOnlyNoticeLabel;

        protected global::System.Web.UI.WebControls.Button
            ContinueButton;
    }
}
