//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFF
{
    public partial class FindBoard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm
            form1;

        protected global::System.Web.UI.WebControls.Label
            AccessNoticeLabel;

        protected global::System.Web.UI.WebControls.Label
            ErrorMessageLabel;

        protected global::System.Web.UI.WebControls.Panel
            AssignedTeamPanel;

        protected global::System.Web.UI.WebControls.Label
            AssignedTeamLabel;

        protected global::System.Web.UI.WebControls.Panel
            TeamFilterPanel;

        protected global::System.Web.UI.WebControls.DropDownList
            TeamDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ShiftDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ProductionLineDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ProductDropDownList;

        protected global::System.Web.UI.WebControls.TextBox
            BoardDateTextBox;

        protected global::System.Web.UI.WebControls.Button
            ClearButton;

        protected global::System.Web.UI.WebControls.Button
            SearchButton;

        protected global::System.Web.UI.WebControls.Label
            ResultCountLabel;

        protected global::System.Web.UI.WebControls.Panel
            EmptyResultsPanel;

        protected global::System.Web.UI.WebControls.Panel
            ResultsTablePanel;

        protected global::System.Web.UI.WebControls.Repeater
            ResultsRepeater;
    }
}
