//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFF
{
    public partial class PB_page
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm
            form1;

        protected global::System.Web.UI.WebControls.HiddenField
            CanEditProductionBoardHiddenField;

        protected global::System.Web.UI.WebControls.HiddenField
            CurrentBoardIdHiddenField;

        protected global::System.Web.UI.WebControls.Label
            ReadOnlyModeLabel;

        protected global::System.Web.UI.WebControls.HyperLink
            PreviousBoardLink;

        protected global::System.Web.UI.WebControls.HyperLink
            NextBoardLink;

        protected global::System.Web.UI.WebControls.Label
            DateLabel;

        protected global::System.Web.UI.WebControls.Label
            ShiftLabel;

        protected global::System.Web.UI.WebControls.Label
            TeamLabel;

        protected global::System.Web.UI.WebControls.Label
            ProductLabel;

        protected global::System.Web.UI.WebControls.Label
            PLLabel;

        protected global::System.Web.UI.WebControls.Label
            h1Label;

        protected global::System.Web.UI.WebControls.Label
            h1Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML1;

        protected global::System.Web.UI.WebControls.Label
            reel_h1;

        protected global::System.Web.UI.WebControls.Label
            h2Label;

        protected global::System.Web.UI.WebControls.Label
            h2Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML2;

        protected global::System.Web.UI.WebControls.Label
            h3Label;

        protected global::System.Web.UI.WebControls.Label
            h3Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML3;

        protected global::System.Web.UI.WebControls.Label
            h4Label;

        protected global::System.Web.UI.WebControls.Label
            h4Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML4;

        protected global::System.Web.UI.WebControls.Label
            h5Label;

        protected global::System.Web.UI.WebControls.Label
            h5Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML5;

        protected global::System.Web.UI.WebControls.Label
            h6Label;

        protected global::System.Web.UI.WebControls.Label
            h6Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML6;

        protected global::System.Web.UI.WebControls.Label
            h7Label;

        protected global::System.Web.UI.WebControls.Label
            h7Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML7;

        protected global::System.Web.UI.WebControls.Label
            h8Label;

        protected global::System.Web.UI.WebControls.Label
            h8Object;

        protected global::System.Web.UI.WebControls.Label
            OBJ_CML8;

        protected global::System.Web.UI.WebControls.Label
            lblCOUCOU;
    }
}
