//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFF
{
    public partial class WeeklySyntheses
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm
            form1;

        protected global::System.Web.UI.WebControls.HiddenField
            ChartDataHiddenField;

        protected global::System.Web.UI.WebControls.Label
            ErrorMessageLabel;

        protected global::System.Web.UI.WebControls.TextBox
            WeekDateTextBox;

        protected global::System.Web.UI.WebControls.DropDownList
            TeamDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ProductionLineDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList
            ProductDropDownList;

        protected global::System.Web.UI.WebControls.Button
            ApplyFilterButton;

        protected global::System.Web.UI.WebControls.Label
            BestTeamLabel;

        protected global::System.Web.UI.WebControls.Label
            TotalTargetLabel;

        protected global::System.Web.UI.WebControls.Label
            TotalActualLabel;

        protected global::System.Web.UI.WebControls.Label
            TotalScrapLabel;

        protected global::System.Web.UI.WebControls.Label
            EfficiencyLabel;

        protected global::System.Web.UI.WebControls.Label
            WeekRangeLabel;

        protected global::System.Web.UI.WebControls.Panel
            EmptyResultsPanel;

        protected global::System.Web.UI.WebControls.Panel
            ResultsTablePanel;

        protected global::System.Web.UI.WebControls.Repeater
            WeeklyResultsRepeater;
    }
}
